Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plot_all_regression_models_of_comfort_vs_intensity(data, models)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 1[0m
[0;32m----> 1[0m [43mplot_all_regression_models_of_comfort_vs_intensity[49m[43m([49m[43mdata[49m[43m,[49m[43m [49m[43mmodels[49m[43m)[49m

File [0;32m~/work/cs345/cs345/utils.py:221[0m, in [0;36mplot_all_regression_models_of_comfort_vs_intensity[0;34m(data, models)[0m
[1;32m    216[0m fig, axes [38;5;241m=[39m plt[38;5;241m.[39msubplots(
[1;32m    217[0m     rows, cols, figsize[38;5;241m=[39m([38;5;241m4.0[39m [38;5;241m*[39m cols, [38;5;241m3.5[39m [38;5;241m*[39m rows), sharex[38;5;241m=[39m[38;5;28;01mTrue[39;00m, 
[1;32m    218[0m )
[1;32m    220[0m [38;5;28;01mfor[39;00m idx, (ax, m) [38;5;129;01min[39;00m [38;5;28menumerate[39m([38;5;28mzip[39m(axes[38;5;241m.[39mflatten(), models)):
[0;32m--> 221[0m     [43mplot_regression_model_of_comfort_vs_intensity[49m[43m([49m[43mdata[49m[43m,[49m[43m [49m[43mm[49m[43m,[49m[43m [49m[43max[49m[43m)[49m
[1;32m    223[0m     ax[38;5;241m.[39mset_title([38;5;124m'[39m[38;5;124mModel [39m[38;5;132;01m{}[39;00m[38;5;124m'[39m[38;5;241m.[39mformat(idx))
[1;32m    224[0m     [38;5;28;01mif[39;00m idx [38;5;241m%[39m cols [38;5;241m==[39m [38;5;241m0[39m:

File [0;32m~/work/cs345/cs345/utils.py:172[0m, in [0;36mplot_regression_model_of_comfort_vs_intensity[0;34m(data, fitted_model, ax)[0m
[1;32m    156[0m [38;5;28;01mdef[39;00m [38;5;21mplot_regression_model_of_comfort_vs_intensity[39m(
[1;32m    157[0m         data, 
[1;32m    158[0m         fitted_model,
[1;32m    159[0m         ax,
[1;32m    160[0m ):
[1;32m    161[0m [38;5;250m    [39m[38;5;124;03m'''[39;00m
[1;32m    162[0m [38;5;124;03m    For use in the evaluation metrics unit: plot the regression models against the data[39;00m
[1;32m    163[0m 
[0;32m   (...)[0m
[1;32m    170[0m [38;5;124;03m        Nothing[39;00m
[1;32m    171[0m [38;5;124;03m    '''[39;00m
[0;32m--> 172[0m     key [38;5;241m=[39m [43mjrandom[49m[38;5;241m.[39mPRNGKey(seed[38;5;241m=[39m[38;5;241m0[39m)
[1;32m    174[0m     test_x [38;5;241m=[39m jnp[38;5;241m.[39mlinspace(
[1;32m    175[0m         data[[38;5;124m'[39m[38;5;124mIntensity[39m[38;5;124m'[39m][38;5;241m.[39mmin(), data[[38;5;124m'[39m[38;5;124mIntensity[39m[38;5;124m'[39m][38;5;241m.[39mmax(), [38;5;241m200[39m,
[1;32m    176[0m     )[[38;5;241m.[39m[38;5;241m.[39m[38;5;241m.[39m, [38;5;28;01mNone[39;00m]
[1;32m    178[0m     samples [38;5;241m=[39m pfml[38;5;241m.[39msample_generative_process(
[1;32m    179[0m         fitted_model, key, [38;5;28mlen[39m(test_x), test_x,
[1;32m    180[0m     )

[0;31mNameError[0m: name 'jrandom' is not defined

