Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
NUM_ITERATIONS = 10000

# Define an optimizer; here we chose the "Adam" algorithm
optimizer = numpyro.optim.Adam(step_size=0.01)

# Pick a random generator seed for the optimizer
key_optimizer = jrandom.PRNGKey(seed=0)

# Fit the model via the MLE
result = pfml.mle(
    univariate_linear_regression, 
    optimizer, 
    key_optimizer, 
    NUM_ITERATIONS,
    len(data), 
    jnp.array(data['Age']), 
    y=jnp.array(data['Telekinetic-Ability']),
)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[6], line 7[0m
[1;32m      4[0m optimizer [38;5;241m=[39m numpyro[38;5;241m.[39moptim[38;5;241m.[39mAdam(step_size[38;5;241m=[39m[38;5;241m0.01[39m)
[1;32m      6[0m [38;5;66;03m# Pick a random generator seed for the optimizer[39;00m
[0;32m----> 7[0m key_optimizer [38;5;241m=[39m [43mjrandom[49m[38;5;241m.[39mPRNGKey(seed[38;5;241m=[39m[38;5;241m0[39m)
[1;32m      9[0m [38;5;66;03m# Fit the model via the MLE[39;00m
[1;32m     10[0m result [38;5;241m=[39m pfml[38;5;241m.[39mmle(
[1;32m     11[0m     univariate_linear_regression, 
[1;32m     12[0m     optimizer, 
[0;32m   (...)[0m
[1;32m     17[0m     y[38;5;241m=[39mjnp[38;5;241m.[39marray(data[[38;5;124m'[39m[38;5;124mTelekinetic-Ability[39m[38;5;124m'[39m]),
[1;32m     18[0m )

[0;31mNameError[0m: name 'jrandom' is not defined

